### ISSUE TITLE
Implement App free tier

### ISSUE THREAD

**Issue by Valebeflo** [pokt-network/pocket-dashboard#190]
Complete application Free tier. 
The free tier is a freemium plan the Dashboard offers to App developers to stake on their behalf with a set of conditions

- Limited to 1 Million Relays per Day
- Access to Application Authentication Token (AAT), but not ownership of the AAT
- Staked POKT is managed by Pocket Network Inc.
- POKT balance unavailable for transfers

HOW THE FREE TIER WORKS?
The free tier is an unlimited time infrastructure plan for any app to receive free API throughput maxed at 1 Million Relays per Day.

In the free tier, Pocket Network Inc stakes on behalf of the customer and manages the staked POKT as well as the AAT (Application Authentication Token). This will allow any app to access the network and connect to any of the available chains for free.

As your the app grows and scales the user will be able to unstake and transition to the Custom Tier (paid version)

**Purchase Invoice**
After the purchase, there is an invoice generated on which some values should be pulled from the purchase information. please, contact me for further details

**Notification**
After the purchase, there is an alert generated which should remain over the app detail screen until the Network confirms the app Is staked. 

** Email Notification**
Once the app is staked an email (is already created on SendGrid) should be sent to the user.

**App Detail**

The Staked tokens and Balance should be expressed on POKT, not UPOKT

Max Relays Per Day should represent the just purchased amount of relays

**NETWORKS**
This table should be showing the information about the stacked chains

**AAT**
The container should show up the app AAT

**Comment by pabelnl** [comment]
Changes available with PR #217
