### ISSUE TITLE
Review App Custom Tier Purchase

### ISSUE THREAD

**Issue by Valebeflo** [pokt-network/pocket-dashboard#191]
**Relays Values**
Please check if the values on the order summary are correct according to the Economics Formula values.
The values reference:
 https://www.notion.so/pocketnetwork/Purchase-Final-Numbers-9b4a110f8bcb4f63918f312c474713cb

**The order Summary** 
On the order Summary contains a "Balance" value which we need to subtract from the total cost of the purchasd amount of relays

Once completed the Purchase...

**Purchase Invoice**
There is an invoice generated on which some values should be pulled from the purchase information. Please, contact me for further details

**Notification**
There here is an alert generated which should remain over the app detail screen until the Network confirms the app Is staked. 

** Email Notification**
Once the app is staked an email (is already created on SendGrid) should be sent to the user.

**Fix APP DETAIL values**

Staked tokens and Balance should be expressed on POKT, not UPOKT

Max Relays Per Day should represent the just purchased  amount of relays

**NETWORKS**
This table should be showing the information about the stacked chains

**Comment by nymd** [comment]
After finishing the Stripe transaction, the "Go to app details" does not link to the actual app

http://localhost:xxxx/dashboard/payment/invoice

the "Go to App details" button links to "http://localhost:xxxx/dashboard/apps/detail/:id"
