### ISSUE TITLE
Formatting Issue on Safari Browser 

### ISSUE THREAD

**Issue by jeremybeal11** [pokt-network/pocket-dashboard#216]
When I open up the dashboard using safari. The page renders as follows(see attachment) 
<img width="1440" alt="Screen Shot 2020-07-20 at 12 39 07 PM" src="https://user-images.githubusercontent.com/23203842/87963494-c94e4600-ca86-11ea-9207-8528abcc989c.png">

**Comment by Evalir** [comment]
Due to the upcoming change in the theming / styling system, we'll be closing this. Thanks!
