### ISSUE TITLE
Reset password doesn't send the email

### ISSUE THREAD

**Issue by pabelnl** [pokt-network/pocket-dashboard#232]
Reset password is not sending the email, using the resend button sents the verify your email instead of reset password.

**Comment by nymd** [comment]
Write your email to reset your password.

to

Enter your email to reset your password.

**Comment by nymd** [comment]
Now that we've found the actual issue:

"Reset password" never makes the user check their email. It asks only one security question and then allows a reset.

Reset password required flow:

- user clicks Reset Password
- email is sent to user with one-time link
- user clicks link in email
- user lands on site where they must answer 2 security questions
- user is then allowed to reset password

**Comment by nymd** [comment]
Recaptcha should be added to the reset question page to mitigate dictionary attacks

**Comment by nymd** [comment]
Security question API call should not return the answer to the question in plain text.
