### ISSUE TITLE
Change db fields to two-way encryption

### ISSUE THREAD

**Issue by nymd** [pokt-network/pocket-dashboard#330]
Using an encryption lib (like crypto with IV), certain fields in the database should be two way encrypted and not stored in plaintext:

- freeTierApplicationAccount
- password recovery answers

The encryption key should be stored in the .env in a variable like "ENCRYPTION_PRIVATE KEY" that is added to the .github/workflow/action files as a $secret.

A separate key should be used for each environment; devs, testnet, mainnet.  The testnet and mainnet keys should be known only to Luis / stored in a company 1Pass vault.

**Comment by pabelnl** [comment]
Merged already.
