### ISSUE TITLE
Apps/Nodes details being displayed on other user accounts.

### ISSUE THREAD

**Issue by emedrano2112** [pokt-network/pocket-dashboard#361]
**Description**:
As a user, I'm logged in to the Dashboard and I can see my nodes and APPs and its detail. But I should not be able to see other users APPs and Nodes from my account, and at the moment that is possible.

**Step by Step**:
1. Go to the dashboard and login with your account.
2. Create or import a node or an APP. Or simply open up one that you have already created. Example:
https://dashboard.testnet.pokt.network/dashboard/nodes/detail/f0a30e7ae08115068104219f349f55affb4179b0
3. Logged into your account, try loading the URL pasted above.
4. Notice that the URL opens up, and loads the node's/App's information that is not yours. You can see all of the node's/APP's details: Address, Public Key, Balance, Status; you can even stake or unstake it. If it's jailed, then unjail it.

**Actual**:
The URL opens up, and loads the node's/App's information that is not yours. You can see all of the node's/APP's details: Address, Public Key, Balance, Status; you can even stake or unstake it. If it's jailed, then unjail it.

**Expected**:
The URL should never open up, since that node/APP is not public, and it's not yours.

**Evidence**:
https://www.loom.com/share/965005e484ef48bb8d12720f5e02a546

**Comment by nymd** [comment]
Covered by #339 and #340
