### ISSUE TITLE
Gateway- No confirmation when adding or saving changes.

### ISSUE THREAD

**Issue by pabelnl** [pokt-network/pocket-dashboard#376]
In gateway settings, no confirmation when "adding a whitelist user agent". The banner above doesn't state specifically what was changed.
In gateway settings, no confirmation when "adding a whitelist original". The banner above doesn't state specifically what was changed.
In gateway settings, no confirmation when "Saving Changes". The banner above doesn't state specifically what was changed.

**Comment by nymd** [comment]
I checked other parts of the dashboard and no other save function tells you what features were saved. Closing.
