### ISSUE TITLE
Error on the unstaking process

### ISSUE THREAD

**Issue by emedrano2112** [pokt-network/pocket-dashboard#400]
**Description**
Cannot unstake node, after providing the key file and passphrase, following error from the BE: {"message":"Cannot read property 'pocketNode' of null","name":"TypeError"}

**Step by Step**

1. Find a node that's staked, and that has the "unstake" button present.
2. Click the unstake button.
3. Provide the node's keyfile and passphrase.
4. Click on Continue.
5. Notice that there's no error message, and the BE is responding with the following error: Cannot read property 'pocketNode' of null","name":"TypeError"

**Comment by wgarcia4190** [comment]
This is a duplicated issue.
Link to the original: https://github.com/pokt-network/pocket-dashboard/issues/392
