### ISSUE TITLE
Session is not expiring after 10-15 mins as configured.

### ISSUE THREAD

**Issue by emedrano2112** [pokt-network/pocket-dashboard#403]
**Description**:
A user has logged in and performed many actions/calls/transactions within its session. At the moment, session must be expired after 15 mins (for testing purposes). That is not being the case, as a user can be off/inactive for hours, return and unsleep his PC and continues on his session.

**Step by Step**

1. Go to the pocket dashboard and login. 
2. Create a new node or APP.
3. Leave the APP open for about 1-2 hours and notice that when coming back, you will still be able to use the APP normally.

**Comment by nymd** [comment]
@wgarcia4190 looking into reproducing this
