### ISSUE TITLE
Newly created node exported via the CLI, not able to be imported.

### ISSUE THREAD

**Issue by emedrano2112** [pokt-network/pocket-dashboard#406]
**Description:**
When creating a node in the CLI, assigning the validator and then exporting it via the dashboard, the following error message and behaviour was found, "Validator not found error message" but node it's still added to the list of nodes: 

**Step by Step**

1. Create a node via the CLI: `pocket accounts create`.
2. Assign the validator to that node: `pocket accounts set-validator <address>`
3. Go to the faucet and claim some test tokens: https://docs.pokt.network/docs/get-test-tokens
4. Wait for the balance to be applied (on the next block).
5. Export the node's accounts to be imported from the dashboard: `pocket accounts export <address>`
6. Now go to the node's section in the dashboard.
7. Click on import.
8. Provide the file exported (and saved with a good editor as .json or .txt), with the passphrase.
9. Notice the error in the BE, but missing error message in the FE.

**Evidence:**
https://www.loom.com/share/0bf329f3727e4df99255ad7ba77c9446

**Comment by nymd** [comment]
Not an issue.

The sequence used for testing above is missing the step of staking the node.

1. Create a node via the CLI: pocket accounts create.
2. Go to the faucet and claim some test tokens: https://docs.pokt.network/docs/get-test-tokens
3. Wait for the balance to be applied (on the next block).
4. Stake your node `pocket --remoteCLIURL https://node1.testnet.pokt.network nodes stake 745ad898797c8d8a51e151f16b4605f2d7759667 15004990000 0002 https://pokt.dev.blockchain.info:443 testnet 10000`
5. Wait for the transaction to verify
6. Assign the validator to that node: pocket accounts set-validator <address>

continue...
