### ISSUE TITLE
/Dashboard URL path should link to the homepage

### ISSUE THREAD

**Issue by emedrano2112** [pokt-network/pocket-dashboard#409]
**Description:**
When clicking on /Dashboard (next to the Pocket Logo), the user must be redirected to the homepage or /dashboard route.

![image](https://user-images.githubusercontent.com/17748171/92958222-37d4d200-f440-11ea-967a-26afe159d3ed.png)

**Comment by pabelnl** [comment]
First, we have the login page and the main screen aka homepage is the network status by design, there is no other homepage.

**Comment by emedrano2112** [comment]
@pabelnl What is meant here, is that the "DASHBOARD" above is "clickable" and when clicked then it redirects to https://dashboard.testnet.pokt.network/dashboard. 

Example, if you're in node's or APP's section, and you click there, then you should be taken to https://dashboard.testnet.pokt.network/dashboard
