### ISSUE TITLE
Landing page- Welcome message

### ISSUE THREAD

**Issue by Valebeflo** [pokt-network/pocket-dashboard#453]
On https://dashboard.testnet.pokt.network/
The welcome message should be: This tool provides a simple way to interact, purchase, and stake with Pocket Network, using real-time network information to manage app and nodes.

This should be erased from the home page welcome message container

**Comment by Valebeflo** [comment]
On the landing page the Nor the logo or the "/Dashboard" is linked to the correct pages:
- [x]  Pocket logo link to: [https://www.pokt.network/](https://www.pokt.network/)
- [x]  "/dashboard" link to: [https://dashboard.testnet.pokt.network/login](https://dashboard.testnet.pokt.network/login)

**Comment by pabelnl** [comment]
@Valebeflo Please provide correct URLs for both Pocket logo and `/ dashboard`.
