### ISSUE TITLE
Gateway endpoint not available

### ISSUE THREAD

**Issue by emedrano2112** [pokt-network/pocket-dashboard#491]
**Description:**
When in the APP's gateway details page, taking the endpoint URL and trying to test it, then a 404 not found is found.

**Evidence:**
https://www.loom.com/share/42c04d5246c14e04ad9c65997940fc69

**Comment by nymd** [comment]
Not an issue; endpoint receives POST only -- you are hitting it with GET in a browser

**Comment by nymd** [comment]
curl --location --request POST 'https://eth-mainnet.gateway.pokt.network/v1/lb/5f6a358b5053d3232349e41d' \
--header 'Authorization: Basic OmM5M2M3MDk0ZTEwNzU0MjdmYzA4MWRmYzU3ZDhiNDg1' \
--header 'Content-Type: application/json' \
--data-raw '{
	"jsonrpc": "2.0",
	"id": 1,
	"method": "eth_getBalance",
	"params": ["0xEA674fdDe714fd979de3EdF0F56AA9716B898ec8", "latest"]
}'

sample use with cURL
