### ISSUE TITLE
Launch offering plan - Stake

### ISSUE THREAD

**Issue by Valebeflo** [pokt-network/pocket-dashboard#494]
The staked value for the apps on the Launch offering plan should be 24.950.100 to get 1 million RPD

**Comment by nymd** [comment]
24,950.1 POKT works out to 999,984 relays -- is this intended?

![image](https://user-images.githubusercontent.com/16605170/94692224-2a946000-02e7-11eb-94ea-3e67001763c3.png)
 @Valebeflo

**Comment by Valebeflo** [comment]
We need to give the user 1 million relays we need to adjust again the POKT staked (the calculator, provided me this value) maybe is affected due to the decimals. I  would need to see the formula used here to provide the exact value to be staked.

**Comment by nymd** [comment]
ok thanks I will have @pabelnl do the math on a better caculator
