### ISSUE TITLE
Node Unjail

### ISSUE THREAD

**Issue by Valebeflo** [pokt-network/pocket-dashboard#526]
**Context:**
When a Node is Jailed the account Stake Status should be **Staked**  and the unstake Button should be disabled
also, TX warning is by default triggered and this should not be displayed until the user performs the Unjail TX.
**Step by Step:**
- Create a node account with a nonexisting Service URL
- Stake a Node account
- Wait for the node to be Jailed
- Go to Node Detail
**Expected output** 
<img width="1231" alt="Screen Shot 2020-10-19 at 10 18 20 AM" src="https://user-images.githubusercontent.com/67430643/96470991-79e9f400-11f4-11eb-9e2b-a159ed925a0a.png">
This warning should not be visible
The Stake status should be Stake (whit this change the Networks should be visible as well as the Service URL)
Unstake Button should be disabled

When the user clicks on "Jail this Node" confirms the account credentials and performs the Unjail tx. >>>The Tx warning should be displayed on the Node Detail until the Node gets out of Jail or the next block is produced
- Stake status should remain Stake
- Jail Statis Should remain YES
- Unstake Button should Remain disable

When The node is out of Jail:
- The Tx warning should disappear (this is currently happening)
- The unstake button should appear (this is currently happening)
-  The email notification should be sent to the user. This is not happening, there is a template on SendGrid
- Stake status should remain Stake
- Jail Statis Should remain YES
- Unstake Button should Remain disable

**Comment by Evalir** [comment]
Closed due to not being deemed as relevant for the upcoming dashboard v2.
