### ISSUE TITLE
App Unstake

### ISSUE THREAD

**Issue by Valebeflo** [pokt-network/pocket-dashboard#527]
**Context:**
There is no unstaking status when an app unstakes
**Step by Step:**
- Use an staked App account
- Click unstake
- Verify account credentials
- On the account app Detail:
<img width="1259" alt="Screen Shot 2020-10-16 at 9 23 33 AM" src="https://user-images.githubusercontent.com/67430643/96481317-fedb0a80-1200-11eb-941d-a3ebdc89bdb4.png">
-There is no warning indicating the Tx was performed
- There is no change on the stake status 
- There is no unstaking timer triggered
- The Gateway button should be disabled

**Expected output**
When the unstake TX is performed
- The Tx warning should appear on the account app Detail immediately after the Tx is performed ( maybe delay on the app status refreshment)
- The Stake status should be switched to UNSTAKING immediately after the Tx is performed and the timer should be visible
- The gateway button should be disabled

When the app is unstaked an email notification should be triggered  ( this is currently working  correctly)

**Comment by Valebeflo** [comment]
Unable to test because the button is deactivated

**Comment by Evalir** [comment]
Closed due to being outdated for the upcoming dashboard v2.
