### ISSUE TITLE
Button Disable state

### ISSUE THREAD

**Issue by Valebeflo** [pokt-network/pocket-dashboard#529]
**Context:**
When the buttons are disabled they disappeared from the user UI
**Step by Step:**
- Stake an App or node account
- Go to ap detail before the Stake tx has been completed
- See that the Unstake button is not visible
**Expected output** 
Change the UI of those invisible buttons the following appearance 
<img width="839" alt="Screen Shot 2020-10-19 at 10 47 21 AM" src="https://user-images.githubusercontent.com/67430643/96515991-e6341a00-122b-11eb-9f3c-ad54d942a347.png">

**Comment by Valebeflo** [comment]
The unstake button is not correctly activated.

When the user stakes an account while the Tx is completed the Stake button should be deactivated
This is not correct->
<img width="1045" alt="Screen Shot 2020-10-30 at 3 50 54 PM" src="https://user-images.githubusercontent.com/67430643/97885423-57c49b80-1cf5-11eb-8a3d-c3ba6b4dba1f.png">
When the account get staked the Unstake button should be activated ad well as the gateway button
This is not correct->
<img width="1234" alt="Screen Shot 2020-11-02 at 10 21 14 AM" src="https://user-images.githubusercontent.com/67430643/97885565-88a4d080-1cf5-11eb-9007-e76f5f3b76c5.png">
<img width="1049" alt="Screen Shot 2020-11-02 at 10 16 38 AM" src="https://user-images.githubusercontent.com/67430643/97885585-8e021b00-1cf5-11eb-91c6-80f604c0dad6.png">

Apps on the Launch offering  plan should not be able to unstake- the Ustake Button should be deactivated
This is not correct->
<img width="1172" alt="Screen Shot 2020-11-02 at 10 25 59 AM" src="https://user-images.githubusercontent.com/67430643/97885809-d7526a80-1cf5-11eb-9a76-aa3f9829e8e9.png">

**Comment by Evalir** [comment]
Closed due to being outdated for the upcoming dashboard v2.
