### ISSUE TITLE
App stake

### ISSUE THREAD

**Issue by Valebeflo** [pokt-network/pocket-dashboard#534]
After the purchase on the app detail, user should see a TX warning until the apps is staked and the unstake button should be activated as well as the gateway settings button

<img width="1277" alt="Screen Shot 2020-10-30 at 3 49 15 PM" src="https://user-images.githubusercontent.com/67430643/97889271-28645d80-1cfa-11eb-8d85-106ea20ff187.png">

**Comment by Evalir** [comment]
Closed due to being outdated for the upcoming dashboard v2.
