### ISSUE TITLE
Inconsistent data on "Network Status" page

### ISSUE THREAD

**Issue by mokn** [pokt-network/pocket-dashboard#551]
On the Network Status page, it is showing 100 nodes and 38M staked POKT. This isn't accurate in terms of the network wide data. If it's pulling from a different CLI command, it should have some context for the user.

**Comment by Evalir** [comment]
Closed due to being outdated for the upcoming dashboard v2. We will build an API off the TimescaleDB database for pulling these metrics in real time.
